### ISSUE TITLE
ES Modules Are Not Supported

### ISSUE THREAD

**Issue by TrySound** [brentlintner/synt#79]
Thanks for your project. There's some issues with js part.
- es modules are not supported in js (ts works fine)
- syntax error is not descriptive which file is failed

**Comment by brentlintner** [comment]
Hey @TrySound, thanks a bunch for the comments and feedback! :-)

Ack! You are totally right. Upon further investigation, it seems the [sourceToken](http://esprima.readthedocs.io/en/latest/syntactic-analysis.html#distinguishing-a-script-and-a-module) property needs to be set to module. I am going to make a quick update today to be able to set that to module or script, and will post here when I do.

I also made a [new issue](https://github.com/brentlintner/synt/issues/81) for logging exactly which file failed when Esprima throws an error.

**Comment by brentlintner** [comment]
PS: Updated the Issue title in case others have the same issue.

**Comment by TrySound** [comment]
Thanks

**Comment by brentlintner** [comment]
@TrySound just published [v0.4.3](https://github.com/brentlintner/synt/releases/tag/0.4.3) with the bug fix and some tests. Should parse modules by default now with an option to parse as a `script` instead. Let me know if there still are issues!
