### ISSUE TITLE
Support transform class properties (ES7+)

### ISSUE THREAD

**Issue by JustFly1984** [brentlintner/synt#92]
I tried to use Synt, but get an error
```
/.nvm/versions/node/v8.0.0/lib/node_modules/synt/lib/similar/javascript.js:64
            throw new Error("in " + filepath + "\n\n" + err.stack);
```

Across whole my `React` app codebase I have class methods declared like:
```
class A extends Component {
  method = () => {
     ...
  }
}
```
This is `babel`'s syntactic sugar, so you do not need to `method.bind(this)` in constructor anymore.

This is a bummer for me.

**Comment by brentlintner** [comment]
Hey @JustFly1984, thanks for opening an issue. :-)

Currently JSX/ES7+ (or Babel specific) syntax is not yet supported or isn't via Esprima. See #91 (and #83 FWIW). Hoping to see if using Babylon can make everything work great, which should rightfully include apps/code like this.

**Comment by brentlintner** [comment]
Closing this specific issue given the creation of #94. :-)

**Comment by brentlintner** [comment]
@JustFly1984 it's been a long time lol, but fwiw the [latest release](https://github.com/brentlintner/synt/releases/tag/0.5.0) should support everything up to ES15 now. 😄

**Comment by brentlintner** [comment]
Still no [JSX support](https://github.com/brentlintner/synt/issues/83) yet though. 😞
